
--IMPORTACION Y LIMPIEZA DE DATOS DE LA TABLA MEDICOS
--======================================================================
CREATE TABLE MEDICO(
	NOMBRE NVARCHAR(40),
	APELLIDO NVARCHAR(40),
	ESPECIALIDAD NVARCHAR(40),
	NUMERO_COLEGIADO INT PRIMARY KEY
);
GO


CREATE TRIGGER LIMPIADOR_INFORMACION_MEDICOS
ON MEDICO AFTER INSERT 
AS
BEGIN



	DECLARE @CANT INT =(SELECT COUNT(*) FROM inserted);
	DECLARE @I INT = 1;

	WHILE @I <= @CANT
	BEGIN

		DECLARE @NOMBRE_NUEVO NVARCHAR(40);
		DECLARE @ESPECIALIDAD NVARCHAR(40);
		DECLARE @APELLIDO_NUEVO NVARCHAR(40);
		DECLARE @MATRICULA INT;




		WITH REGISTROS_INSERTADOS AS(
			SELECT *
			,ROW_NUMBER() OVER (ORDER BY NUMERO_COLEGIADO) AS NRO
			FROM inserted
		)
		SELECT @NOMBRE_NUEVO=R.APELLIDO
		,@APELLIDO_NUEVO=R.NOMBRE
		,@ESPECIALIDAD=R.ESPECIALIDAD
		,@MATRICULA=R.NUMERO_COLEGIADO
		FROM REGISTROS_INSERTADOS R
		WHERE R.NRO=@I



		--LIMPIEZA APELLIDO
		DECLARE @POS_ESPACIO INT = (CHARINDEX(' ', @APELLIDO_NUEVO));
		IF @POS_ESPACIO <> 0
		BEGIN
			DECLARE @LONG_APELLIDO INT = LEN(@APELLIDO_NUEVO);
			SET @APELLIDO_NUEVO = LOWER(SUBSTRING(@APELLIDO_NUEVO,@POS_ESPACIO,@LONG_APELLIDO));
		END

	
		--LIMPIEZA NOMBRE
		DECLARE @POS_PUNTO INT = CHARINDEX('.',@NOMBRE_NUEVO);
		IF @POS_PUNTO <> 0
			BEGIN
				DECLARE @LONG_NOMBRE INT = LEN(@NOMBRE_NUEVO);
				DECLARE @LONG_MAX INT = @POS_PUNTO-3;
				--PRINT @LONG_MAX;
				SET @NOMBRE_NUEVO = SUBSTRING(@NOMBRE_NUEVO,1,@LONG_MAX);
			END
		SET @NOMBRE_NUEVO=LOWER(@NOMBRE_NUEVO);


		SET @ESPECIALIDAD = LOWER(@ESPECIALIDAD);

	

		UPDATE MEDICO SET NOMBRE=@NOMBRE_NUEVO, APELLIDO=@APELLIDO_NUEVO, ESPECIALIDAD=@ESPECIALIDAD 
		WHERE NUMERO_COLEGIADO=@MATRICULA

		SET @I=@I+1;
	END
	
END

GO


BULK INSERT MEDICO
FROM 'C:\Users\facun\OneDrive\Escritorio\cuarta entrega bbdd\Medicos.csv'
WITH(
	FIELDTERMINATOR=';',
	ROWTERMINATOR='\n',
	KEEPIDENTITY,
	FIRSTROW = 2,
	FIRE_TRIGGERS,
	CODEPAGE = '65001'
)
GO

--======================================================================

--IMPORTACION Y LIMPIEZA DE DATOS DE LA TABLA PACIENTES

--======================================================================


CREATE TABLE PACIENTE(
	NOMBRE NVARCHAR(40),
	APELLIDO NVARCHAR(40),
	FECHA_NAC DATE,
	TIPO_DNI CHAR(3),
	NRO_DOC INT PRIMARY KEY,
	SEXO CHAR(9),
	GENERO VARCHAR(6),
	TELEFONO CHAR(14),
	NACIONALIDAD VARCHAR(40),
	MAIL VARCHAR(40),
	DIRECCION VARCHAR(60),
	LOCALIDAD VARCHAR(60),
	PROVINCIA VARCHAR(60)
);
GO


CREATE TRIGGER LIMPIADOR_INFORMACION_PACIENTES
ON PACIENTE AFTER INSERT 
AS
BEGIN



	DECLARE @CANT INT =(SELECT COUNT(*) FROM inserted);
	DECLARE @I INT = 1;

	WHILE @I <= @CANT
	BEGIN

			DECLARE	@FECHA_NAC DATE,
			@SEXO CHAR(9),
			@DIRECCION VARCHAR(40),
			@LOCALIDAD VARCHAR(40),
			@PROVINCIA VARCHAR(40),
			@NRO_DOC INT;


		WITH REGISTROS_INSERTADOS AS(
			SELECT *
			,ROW_NUMBER() OVER (ORDER BY NRO_DOC) AS NRO_REG
			FROM inserted
		)
		SELECT @FECHA_NAC=convert(datetime,R.FECHA_NAC, 103),
		@SEXO=LOWER(R.SEXO),
		@DIRECCION=LOWER(R.DIRECCION),
		@LOCALIDAD=LOWER(R.LOCALIDAD),
		@PROVINCIA=LOWER(R.PROVINCIA),
		@NRO_DOC=R.NRO_DOC
		FROM REGISTROS_INSERTADOS R
		WHERE R.NRO_REG=@I


		UPDATE PACIENTE SET FECHA_NAC=@FECHA_NAC,
		SEXO = @SEXO,
		DIRECCION = @DIRECCION,
		LOCALIDAD = @LOCALIDAD,
		PROVINCIA = @PROVINCIA
		WHERE NRO_DOC=@NRO_DOC
		
		SET @I=@I+1;
	END
	
END

GO


BULK INSERT PACIENTE
FROM 'C:\Users\facun\OneDrive\Escritorio\cuarta entrega bbdd\Pacientes.csv'
WITH(
	FIELDTERMINATOR=';',
	ROWTERMINATOR='\n',
	KEEPIDENTITY,
	FIRSTROW = 2,
	FIRE_TRIGGERS,
	CODEPAGE = '65001'
)
GO

--======================================================================

--IMPORTACION Y LIMPIEZA DE DATOS DE LA TABLA PRESTADOR

--======================================================================


CREATE TABLE PRESTADOR(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	PRESTADOR VARCHAR(40),
	PLAN_PREST VARCHAR(40)
)
GO

CREATE TABLE PRESTADOR_AUX(
	PRESTADOR VARCHAR(40),
	PLAN_PREST VARCHAR(40)
)
GO


CREATE TRIGGER IMPORTADO_PRESTADOR
ON PRESTADOR_AUX AFTER INSERT 
AS
BEGIN



	DECLARE @CANT INT =(SELECT COUNT(*) FROM inserted);
	DECLARE @I INT = 1;

	WHILE @I <= @CANT
	BEGIN

			DECLARE @PRESTADOR VARCHAR(40),
			@PLAN_PREST VARCHAR(40);


		WITH REGISTROS_INSERTADOS AS(
			SELECT *
			,ROW_NUMBER() OVER (ORDER BY PRESTADOR) AS NRO_REG
			FROM inserted
		)
		SELECT @PRESTADOR=R.PRESTADOR,
		@PLAN_PREST=REPLACE(R.PLAN_PREST,';','')
		FROM REGISTROS_INSERTADOS R
		WHERE R.NRO_REG=@I


		INSERT INTO PRESTADOR VALUES (@PRESTADOR,@PLAN_PREST);
		
		SET @I=@I+1;
	END
	
END

GO

BULK INSERT PRESTADOR_AUX
FROM 'C:\Users\facun\OneDrive\Escritorio\cuarta entrega bbdd\Prestador.csv'
WITH(
	FIELDTERMINATOR=';',
	FIRE_TRIGGERS,
	ROWTERMINATOR='\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)
GO

--======================================================================

--IMPORTACION Y LIMPIEZA DE DATOS DE LA TABLA SEDES

--======================================================================
CREATE TABLE SEDE(
	SEDE VARCHAR(40)
	,DIRECCION VARCHAR(40)
	,LOCALIDAD VARCHAR(40)
	,PROVINCIA VARCHAR(40)
)
GO

CREATE TRIGGER IMPORTADO_SEDES
ON SEDE AFTER INSERT 
AS
BEGIN



	DECLARE @CANT INT =(SELECT COUNT(*) FROM inserted);
	DECLARE @I INT = 1;

	WHILE @I <= @CANT
	BEGIN

			DECLARE @SEDE VARCHAR(40)
			,@DIRECCION VARCHAR(40)
			,@LOCALIDAD VARCHAR(40)
			,@PROVINCIA VARCHAR(40);
			/*

		WITH REGISTROS_INSERTADOS AS(
			SELECT *
			,ROW_NUMBER() OVER (ORDER BY PRESTADOR) AS NRO_REG
			FROM inserted
		)
		SELECT @PRESTADOR=R.PRESTADOR,
		@PLAN_PREST=REPLACE(R.PLAN_PREST,';','')
		FROM REGISTROS_INSERTADOS R
		WHERE R.NRO_REG=@I


		INSERT INTO PRESTADOR VALUES (@PRESTADOR,@PLAN_PREST);*/
		
		SET @I=@I+1;
	END
	
END

GO

BULK INSERT SEDE
FROM 'C:\Users\facun\OneDrive\Escritorio\cuarta entrega bbdd\Sedes.csv'
WITH(
	FIELDTERMINATOR=';',
	FIRE_TRIGGERS,
	ROWTERMINATOR='\n',
	FIRSTROW = 2,
	CODEPAGE = '65001'
)
GO